### ISSUE TITLE
DOCKER 里能否加入汉语拼音输入法呢？

### ISSUE THREAD

**Issue by cn3c3p** [x11vnc/docker-desktop#2]
我也感觉有的不是很安全，不仅仅是密码问题。

**Comment by xmjiao** [comment]
I added an image with Chinese localization. Re-download the script `ubuntu_desktop.py` at https://raw.githubusercontent.com/x11vnc/docker-desktop/master/ubuntu_desktop.py and run the command

```
python ubuntu_desktop.py -t zh_CN -p -r
```

The '-p' option will pull the latest image and the '-r' option resets the configuration. You don't need to use the '-r' option in future later.
